# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171016_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('0', 'loved story'), ('1', 'commented on story'), ('2', 'forked a story'), ('3', 'published story'), ('4', 'published book'), ('5', 'added story to book'), ('6', 'followed'), ('7', 'you followed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
