# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('edit_date', models.DateTimeField(verbose_name='date changed')),
                ('view_count', models.IntegerField(default=0)),
                ('ink', models.TextField(blank=True)),
                ('json', models.TextField(blank=True)),
            ],
        ),
    ]
