# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0002_auto_20160401_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='message',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
