# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0003_auto_20160403_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='err_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
