# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User

def update_authors(apps, schema_editor):
    u = User.objects.first()
    if not u:
        u = User(username="default", first_name="Various", last_name="Authors")
        u.save()
        
    for story in apps.get_model("unfold_studio", "Story").objects.all():
        story.author_id = u.id
        story.save()

def revert_authors(apps, schema_editor):
    for story in apps.get_model("unfold_studio", "Story").objects.all():
        story.author = "Anonymous"
        story.save()

class Migration(migrations.Migration):


    dependencies = [
        ('unfold_studio', '0004_story_err_line'),
        ('literacy_events', '0004_auto_20190404_1656'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=revert_authors),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(update_authors, reverse_code=migrations.RunPython.noop)
    ]
