# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0005_auto_20171016_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
