# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('unfold_studio', '0008_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='loves',
            field=models.ManyToManyField(related_name='loved_stories', to='profiles.Profile'),
        ),
    ]
