# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0009_story_loves'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='unfold_studio.Story'),
        ),
    ]
