# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0011_auto_20171016_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='loves',
            field=models.ManyToManyField(blank=True, null=True, related_name='loved_stories', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='unfold_studio.Story'),
        ),
    ]
