# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0012_auto_20171017_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='loves',
            field=models.ManyToManyField(blank=True, related_name='loved_stories', to='profiles.Profile'),
        ),
    ]
