# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 00:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0013_auto_20171017_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 0, 46, 19, 138033, tzinfo=utc), verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 0, 46, 25, 687781, tzinfo=utc), verbose_name='date changed'),
            preserve_default=False,
        ),
    ]
