# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0016_auto_20171024_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-edit_date']},
        ),
    ]
