# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-27 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0017_auto_20171027_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['edit_date']},
        ),
    ]
