# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0020_story_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='includes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_by', to='unfold_studio.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
