# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-28 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('unfold_studio', '0023_auto_20180206_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
        migrations.AddField(
            model_name='story',
            name='sites',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
