# Generated by Django 2.1.2 on 2018-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0027_auto_20181022_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyerror',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
