# Generated by Django 2.1.2 on 2018-11-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0030_auto_20181031_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='book',
            name='priority',
            field=models.FloatField(default=0),
        ),
    ]
