# Generated by Django 2.1.2 on 2018-11-05 16:55

from django.db import migrations

def delete_duplicate_events(apps, schema_editor):
    """
    In preparation for a uniqueness constraint, delete events beyond the first sharing:
     - event_type
     - user_id
     - story
     - book
    """
    Event = apps.get_model('profiles', 'Event')
    unique_together = ["event_type", "user_id", "subject_id", "story_id", "book_id"]
    for e, u, su, st, b in Event.objects.values_list(*unique_together).distinct():
        duplicates = Event.objects.filter(event_type=e, user_id=u, subject_id=su, story_id=st, book_id=b).all()[1:]
        for d in duplicates:
            d.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0031_auto_20181101_0355'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_events, reverse_code=migrations.RunPython.noop),
    ]
