# Generated by Django 2.1.7 on 2019-04-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0034_auto_20190402_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyerror',
            options={'ordering': ['line']},
        ),
    ]
