# Generated by Django 2.2 on 2019-04-30 22:47

from django.db import migrations
from django.contrib.postgres.search import SearchVector

def update_search_vectors(apps, schema_editor):
    Story = apps.get_model('unfold_studio', 'Story')
    Story.objects.update(search=SearchVector('title', 'ink'))

class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0036_auto_20190430_2228'),
    ]

    operations = [
        migrations.RunPython(update_search_vectors)
    ]
