# Generated by Django 5.2.1 on 2026-05-28 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy_events', '0010_auto_20190930_2109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='literacyevent',
            name='event_type',
            field=models.CharField(choices=[('loved_story', 'Loved story'), ('commented', 'Commented on story'), ('forked', 'Forked a story'), ('published_story', 'Published story'), ('unpublished_story', 'Unpublished story'), ('published_book', 'Published book'), ('added_to_book', 'Added story to book'), ('removed_from_book', 'Removed story from book'), ('followed', 'Followed'), ('unfollowed', 'Unfollowed'), ('signed_up', 'Signed up'), ('created_prompt', 'Created prompt'), ('submitted_to_prompt', 'Submitted to prompt'), ('removed_from_prompt', 'Removed from prompt'), ('read_story', 'Read story'), ('published_as_book', 'Published prompt as book'), ('unpublished_book', 'Unpublished prompt book'), ('tagged_version', 'Tagged story version'), ('joined_group', 'Joined literacy group'), ('left_group', 'Left literacy group')], max_length=20),
        ),
        migrations.AlterField(
            model_name='literacyevent',
            name='object_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_events_as_object', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literacyevent',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='literacy_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
