# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        #('unfold_studio', '0010_story_parent'),
        ('unfold_studio', '0002_auto_20160401_2103'),
        ('profiles', '0002_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('0', 'loved story'), ('1', 'commented on story'), ('2', 'published story'), ('3', 'published book'), ('4', 'added story to book'), ('5', 'followed')], max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unfold_studio.Book')),
                ('story', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unfold_studio.Story')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('user', 'event_type', 'subject', 'book', 'story')]),
        ),
    ]
