# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171016_1933'),
    ]

    operations = [
        # Moved all ops to 0001
    ]
