# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171016_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(null=True, related_name='followers', to='profiles.Profile'),
        ),
    ]
