# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20171017_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unfold_studio.Book'),
        ),
        migrations.AlterField(
            model_name='event',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unfold_studio.Story'),
        ),
    ]
