# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20171017_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-timestamp',)},
        ),
    ]
