# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20171024_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
