# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_event_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('0', 'loved story'), ('1', 'commented on story'), ('2', 'forked a story'), ('3', 'published story'), ('4', 'published book'), ('5', 'added story to book'), ('6', 'followed'), ('7', 'you followed'), ('8', 'signed up')], max_length=1),
        ),
    ]
