# Generated by Django 5.0.6 on 2025-01-24 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_is_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
