# Generated by Django 5.2.1 on 2026-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_researcher',
            field=models.BooleanField(default=False),
        ),
    ]
