# Generated by Django 5.2.1 on 2026-05-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_add_is_researcher'),
        ('unfold_studio', '0043_add_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_featured_by', to='unfold_studio.story'),
        ),
    ]
