# Generated by Django 5.2.1 on 2026-05-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_add_profile_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeprecatedUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('new_username', models.CharField(max_length=150)),
                ('renamed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
