# Generated by Django 2.1.7 on 2019-04-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_auto_20190401_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptstory',
            options={'verbose_name_plural': 'Prompt stories'},
        ),
    ]
