# Generated by Django 2.1.7 on 2019-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_auto_20190402_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
