# Generated by Django 2.2.5 on 2019-09-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0010_prompt_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
