# Generated by Django 5.2.1 on 2026-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0012_auto_20190926_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
