# Generated by Django 5.2.1 on 2026-04-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0012_auto_20190926_2304'),
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptstory',
            name='submitted_story_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reversion.version'),
        ),
    ]
