# Generated by Django 2.2.5 on 2019-09-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0013_auto_20181031_2124'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteracyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('accepting_new_members', models.BooleanField(default=False)),
                ('password_required', models.BooleanField(default=False)),
                ('password', models.TextField(blank=True, null=True)),
                ('leaders', models.ManyToManyField(related_name='literacy_groups_leading', to='profiles.Profile')),
                ('members', models.ManyToManyField(related_name='literacy_groups', to='profiles.Profile')),
                ('site', models.ForeignKey(on_delete='cascade', to='sites.Site')),
            ],
        ),
    ]
