# Generated by Django 2.2.5 on 2019-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20181031_2124'),
        ('prompts', '0009_auto_20190926_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(null=True, on_delete='cascade', to='profiles.Profile'),
        ),
    ]
