# Generated by Django 2.2.5 on 2019-09-26 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0011_auto_20190926_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
