@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS2/vuejs.puml
!include DEVICONS/django.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/user_graduate.puml
!include FONTAWESOME/chart_area.puml

LAYOUT_WITH_LEGEND()

Enterprise_Boundary(school, "School"){
  Person(students, "Students", "In formal classrooms", $sprite="users-class")
  Person(teachers, "Teachers", "In formal classrooms", $sprite="user_graduate")
}
Person(users, "Everyday people", "Telling stories", $sprite="users")
Person(researchers, "Researchers", "Studying user behavior", $sprite="chart_area")
System(frontend, "Front end", "vuejs", "The main interface that the customer interacts with", $sprite="vuejs")
System(backend, "Back end", "django", "Handles all business logic", $sprite="java")

Rel(students, frontend, "Uses")
Rel(students, frontend, "Uses")
Rel(spa, api, "Uses", "https")
Rel_R(api, db, "Reads/Writes")
@enduml
