# Generated by Django 5.1.5 on 2025-01-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextGenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField()),
                ('hashed_key', models.CharField(max_length=64)),
                ('prompt', models.TextField()),
                ('context', models.JSONField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backend_name', models.CharField(max_length=64)),
            ],
        ),
    ]
