# Generated by Django 5.1.5 on 2025-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textgenerationrecord',
            old_name='backend_name',
            new_name='backend_config_hash',
        ),
        migrations.AddField(
            model_name='textgenerationrecord',
            name='backend_config',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
