# Generated by Django 5.1.5 on 2025-02-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0002_rename_backend_name_textgenerationrecord_backend_config_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTransitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_play_instance_uuid', models.UUIDField()),
                ('previous_story_timeline', models.JSONField()),
                ('target_knot_data', models.JSONField()),
                ('user_input', models.CharField(max_length=256)),
                ('ai_decision', models.JSONField()),
                ('ai_evaluation', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]