# Generated by Django 5.1.5 on 2025-03-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_generation', '0003_storytransitionrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textgenerationrecord',
            old_name='context',
            new_name='messages',
        ),
        migrations.RenameField(
            model_name='textgenerationrecord',
            old_name='hashed_key',
            new_name='messages_hash',
        ),
        migrations.RemoveField(
            model_name='textgenerationrecord',
            name='prompt',
        ),
    ]
