# Generated by Django 2.1.7 on 2019-04-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literacy_events', '0002_auto_20190331_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-event__timestamp',)},
        ),
    ]
