# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 21:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='story',
            name='edit_date',
        ),
        migrations.RemoveField(
            model_name='story',
            name='view_count',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stories', models.ManyToManyField(to='unfold_studio.Story')),
            ],
        ),
    ]
