# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0006_story_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
