# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0021_auto_20180205_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-priority']},
        ),
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.FloatField(default=0),
        ),
    ]
