# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0022_auto_20180206_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stories',
            field=models.ManyToManyField(related_name='books', to='unfold_studio.Story'),
        ),
    ]
