# Generated by Django 2.1.2 on 2018-10-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('unfold_studio', '0025_auto_20181008_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.IntegerField(choices=[(100, 'PREPROCESS_ERROR'), (101, 'PREPROCESS_INCLUDE_BAD_KEY'), (102, 'PREPROCESS_INCLUDE_STORY_NOT_FOUND'), (103, 'PREPROCESS_INCLUDE_STORY_HAS_ERRORS'), (200, 'COMPILE_ERROR'), (201, 'COMPILE_SYNTAX_KNOT_NAME'), (220, 'COMPILE_SYNTAX_VAR_INCREMENT'), (260, 'COMPILE_MISSING_DIVERT_TARGET'), (400, 'RUNTIME_WARNING'), (401, 'RUNTIME_LOOSE_END'), (0, 'OTHER')], default=0)),
                ('line', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='err_line',
        ),
        migrations.RemoveField(
            model_name='story',
            name='message',
        ),
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
        migrations.RemoveField(
            model_name='story',
            name='includes',
        ),
        migrations.AddField(
            model_name='story',
            name='includes',
            field=models.ManyToManyField(blank=True, related_name='included_by', to='unfold_studio.Story'),
        ),
        migrations.AddField(
            model_name='storyerror',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='unfold_studio.Story'),
        ),
        migrations.AddField(
            model_name='storyerror',
            name='story_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reversion.Version'),
        ),
    ]
