# Generated by Django 2.1.7 on 2019-04-02 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0033_book_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-priority'], 'verbose_name_plural': 'Stories'},
        ),
    ]
