# Generated by Django 2.2 on 2019-04-30 22:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0035_auto_20190411_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='story',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='unfold_stud_search_bfebd6_gin'),
        ),
    ]
