# Generated by Django 5.1.5 on 2025-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0038_auto_20190506_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
    ]
