# Generated by Django 5.1.5 on 2025-01-17 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0038_auto_20190506_1613'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPlayInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('TERMINATED', 'TERMINATED')], default='IN_PROGRESS', max_length=32)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_play_instances', to='unfold_studio.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_play_instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPlayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('story_point', models.IntegerField()),
                ('data_type', models.CharField(choices=[('AI_GENERATED_TEXT', 'AI_GENERATED_TEXT'), ('AUTHORS_TEXT', 'AUTHORS_TEXT'), ('AUTHORS_CHOICE_LIST', 'AUTHORS_CHOICE_LIST'), ('AUTHORS_INPUT_BOX', 'AUTHORS_INPUT_BOX'), ('READERS_ENTERED_TEXT', 'READERS_ENTERED_TEXT'), ('READERS_CHOSEN_CHOICE', 'READERS_CHOSEN_CHOICE')], max_length=30)),
                ('data', models.JSONField()),
                ('story_play_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='unfold_studio.storyplayinstance')),
            ],
        ),
    ]
