# Generated by Django 5.1.5 on 2025-01-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0039_storyplayinstance_storyplayrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyplayrecord',
            name='story_point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storyplayrecord',
            name='data_type',
            field=models.CharField(choices=[('AI_GENERATED_TEXT', 'AI_GENERATED_TEXT'), ('AUTHORS_TEXT', 'AUTHORS_TEXT'), ('AUTHORS_CHOICE_LIST', 'AUTHORS_CHOICE_LIST'), ('AUTHORS_INPUT_BOX', 'AUTHORS_INPUT_BOX'), ('READERS_ENTERED_TEXT', 'READERS_ENTERED_TEXT'), ('READERS_CHOSEN_CHOICE', 'READERS_CHOSEN_CHOICE')], max_length=30),
        ),
    ]
