# Generated by Django 5.1.7 on 2025-04-19 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unfold_studio", "0039_story_description_storyplayinstance_storyplayrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storyplayrecord",
            options={"ordering": ["story_point"]},
        ),
        migrations.AlterField(
            model_name="storyplayinstance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_play_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
