# Generated by Django 5.2.1 on 2026-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0040_alter_storyplayrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
