# Generated by Django 5.2.1 on 2026-04-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0040_alter_storyplayrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
