# Generated by Django 5.2.1 on 2026-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0041_story_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
