# Generated by Cursor on 2026-05-04

from django.db import migrations


def _to_jsonb_sql(table: str, column: str) -> str:
    # Postgres JSONField should be jsonb. Some environments ended up with `json`,
    # which breaks psycopg's Jsonb adapter (attempts to send `Jsonb(...)`).
    return f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute a
        JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
        WHERE c.relname = '{table}'
          AND n.nspname = 'public'
          AND a.attname = '{column}'
          AND t.typname = 'json'
          AND a.attnum > 0
          AND NOT a.attisdropped
    ) THEN
        EXECUTE 'ALTER TABLE public.{table} ALTER COLUMN {column} TYPE jsonb USING {column}::jsonb';
        EXECUTE 'ALTER TABLE public.{table} ALTER COLUMN {column} SET DEFAULT ''[]''::jsonb';
    END IF;
END
$$;
""".replace("{table}", table).replace("{column}", column)


class Migration(migrations.Migration):
    dependencies = [
        ("unfold_studio", "0042_book_genres"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_to_jsonb_sql("unfold_studio_story", "genres"),
            reverse_sql="""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute a
        JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
        WHERE c.relname = 'unfold_studio_story'
          AND n.nspname = 'public'
          AND a.attname = 'genres'
          AND t.typname = 'jsonb'
          AND a.attnum > 0
          AND NOT a.attisdropped
    ) THEN
        EXECUTE 'ALTER TABLE public.unfold_studio_story ALTER COLUMN genres TYPE json USING genres::json';
        EXECUTE 'ALTER TABLE public.unfold_studio_story ALTER COLUMN genres SET DEFAULT ''[]''::json';
    END IF;
END
$$;
""",
        ),
        migrations.RunSQL(
            sql=_to_jsonb_sql("unfold_studio_book", "genres"),
            reverse_sql="""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_attribute a
        JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        JOIN pg_catalog.pg_type t ON t.oid = a.atttypid
        WHERE c.relname = 'unfold_studio_book'
          AND n.nspname = 'public'
          AND a.attname = 'genres'
          AND t.typname = 'jsonb'
          AND a.attnum > 0
          AND NOT a.attisdropped
    ) THEN
        EXECUTE 'ALTER TABLE public.unfold_studio_book ALTER COLUMN genres TYPE json USING genres::json';
        EXECUTE 'ALTER TABLE public.unfold_studio_book ALTER COLUMN genres SET DEFAULT ''[]''::json';
    END IF;
END
$$;
""",
        ),
    ]

