# Generated by Django 5.2.1 on 2026-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0042_story_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
