# Generated by Django 5.2.1 on 2026-05-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0043_add_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='public',
        ),
    ]
