# Generated by Django 5.2.1 on 2026-05-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfold_studio', '0044_remove_story_public_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='story',
            name='sites',
        ),
    ]
