# Generated by Django 5.2.1 on 2026-05-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy_groups', '0004_literacygroup_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='literacygroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
