# Generated by Django 5.2.1 on 2026-03-27 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literacy_groups', '0005_remove_literacygroup_anyone_can_join_joincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joincode',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='literacy_groups.literacygroup'),
        ),
    ]
