# Generated by Django 5.2.1 on 2026-05-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literacy_groups', '0006_add_joincode_remove_anyone_can_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literacygroup',
            name='site',
        ),
    ]
