name: Deploy via SSH

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAgEAzVpFS3pgB1Soia31UI+wikeRzJ6ZnnqOHs4QthApgj7NXJlqzaKb
          xzV2kWXuvzb+89M8jT4zWLh83O6823jh+lp92N1CKbAsbUn4Ddw/FRDOgKRHTs/Nj/ghlX
          mX8T7C2OlzsmfacKxPtnj3/xOAAEOhFG1EoWof4RrGVFMjA0pI9zLjjnCTG8XwlXJHLM1H
          +ycz0p0ztEDS1trGDKx7SuWvZlnYhzLKug0dY5mtmFvIel6BeWrjnGWwI2+hKU5ftN+kDK
          r3iPt8tkXhPUyB/aeYmaLXsD8IcF/Txp5mqSw6wY4jv2WY9XYHJV/VsayuA0E2xg4PwQLP
          3mjSou+XBiVnoiD5HlWDJnOxocb0WGtZwHXtklkOQPNfT2q1W/K4SpXv1zcc3BTPAiHKbZ
          iR4RcwKFM1HpeULY0W0kGpgbN3V6C/fScEb29qYJe2k9CrCADfhr3gMFecW6mCKd8cm4yL
          uexbn+ElqV4Bq91vz3Gq1iPS4lOhj7U54sea/ImpS0XVZD7Zp46WdbTt1tZw+Ugd76P+3D
          yvqDNNikRC9GI8Nv47d1Unn7Ni4a3NxZzbyXOQIIXpN9HU4jBTHUlbrh7CRZ38X+qlxuSf
          c5zpZocVgb03jNgvqgVF/dgIRDioYt0ihRIXgyFT8GFpAEI1Xt/Gw47XREFE8Q8x8ZzlCr
          UAAAdg6W9lQ+lvZUMAAAAHc3NoLXJzYQAAAgEAzVpFS3pgB1Soia31UI+wikeRzJ6ZnnqO
          Hs4QthApgj7NXJlqzaKbxzV2kWXuvzb+89M8jT4zWLh83O6823jh+lp92N1CKbAsbUn4Dd
          w/FRDOgKRHTs/Nj/ghlXmX8T7C2OlzsmfacKxPtnj3/xOAAEOhFG1EoWof4RrGVFMjA0pI
          9zLjjnCTG8XwlXJHLM1H+ycz0p0ztEDS1trGDKx7SuWvZlnYhzLKug0dY5mtmFvIel6BeW
          rjnGWwI2+hKU5ftN+kDKr3iPt8tkXhPUyB/aeYmaLXsD8IcF/Txp5mqSw6wY4jv2WY9XYH
          JV/VsayuA0E2xg4PwQLP3mjSou+XBiVnoiD5HlWDJnOxocb0WGtZwHXtklkOQPNfT2q1W/
          K4SpXv1zcc3BTPAiHKbZiR4RcwKFM1HpeULY0W0kGpgbN3V6C/fScEb29qYJe2k9CrCADf
          hr3gMFecW6mCKd8cm4yLuexbn+ElqV4Bq91vz3Gq1iPS4lOhj7U54sea/ImpS0XVZD7Zp4
          6WdbTt1tZw+Ugd76P+3DyvqDNNikRC9GI8Nv47d1Unn7Ni4a3NxZzbyXOQIIXpN9HU4jBT
          HUlbrh7CRZ38X+qlxuSfc5zpZocVgb03jNgvqgVF/dgIRDioYt0ihRIXgyFT8GFpAEI1Xt
          /Gw47XREFE8Q8x8ZzlCrUAAAADAQABAAACAFUX5AEL28EN5qzupenVMQ2L7LHCwtt143CG
          aUxYVCsBhS2q8SP3DuA0mkZT2+PmkS1OShgpPzOzdyJB14aGh/WrC90Sinkl5LMA5MYxjv
          5WsYuDB310BLV0183NzhWMsUcbLfMur8jizkFJzVIorXDulVAWm0rb5AvugWKt9KNHZAbz
          UnJS2dK3aiMzcKTzB7HeI85Rj/xQpE2d6FWWH50AonciIeScOn9wMc50/wdUeTWj9bjvfx
          Pu21dDyZ+JN4WG6r7JFbvwolQRju1Mx8zpZwW7Ae+pnwCZ5PK37siJaGuOT+fe3MxSNVHa
          bX2rlYwJuP3HE+YiGSsLesVDzOtj4iTM9vHU9dyRMVZvtcg/mBYfOpseWmAm1WBTi7BYi8
          2Ov7E+4n/h0UkCnYUSRnJUDjTDQt1g8TxPdEWWSHTvp/IzQmmdREJ0mamsPLy7YD8WJClb
          6c1FEqn4QvGJd+dCvQTHBOcWnqNfjd4orUN7X103XLlBQznRABe+COqkMmkKnO9wmV4/uL
          HNrNckQ+3m9fsnZMN1ux4s5MpVRN8Q7GCry6rcsGsukXG442XBI6maTsjH0gK4Y7J2Q8sC
          onyQqrhHwpl43TUy0Q6clRTh7TbxB7tAczF2d3bCQFmbJq+OigHkSgoIOj6/pPLyAXaYGg
          sxLfb0ub6XkrWGM90hAAABAQC9gAo4n8bdfnjnBOdeByp+gE2a0zfXO0XXYdR5PGw5iLKK
          DkGvu7X5NOvpRRI0prYDkV47CBL9FfpFm4bmPxH3D7a3Ak5UzG3CiwKxODlCsaaTn+jJaL
          Srd8kyWOePphQbWXmXRiXZQNCqEbr2u7bbcpvOUuqFnZlgPjKFqiVjOMWBwlZJAQlh5RYr
          tsYv2V9vdDD0j7vDrvilIAbiVEbncb7XrLMjTMKsLqGqXAZfzH32ibfS64dSCfP+NmR+dn
          y8zPld+gjJ/GDfJJql7ZXU7noGDo3BVzIY5jkhjmYB9K9IiyeT0VOTn90/bpmdZyj5raN8
          /euIDsiPgZ30HLywAAABAQDvIXLAOyUdyHtwAQExYKhZebIr+jREJOzerVuCU9yWuaGtJL
          m2raevGmGQwiNY0lcOjMsllJLA7aicB32i2ZnbDpu3tlgpeXryCy4bDI0TJBqm4tddIi3M
          WL7i4dGQ4NnokDcj6akzsqF9JEpWTD5FNG0gPn5iQskBTFbacukgrXcoU6G+bWbjPZWjAr
          GTK2e+5nz5o6k3PbEbPfk9Bhb8pksc5EFuYAZL8H93NWS+OhJvCQsg/eN5psJKoSmk9/Hs
          AS17yPi8lF+ib0SCxt+8E+ikKBOKj843FP3sD5xrBsf8J1RjAxWBDzU9xwbH3SuAg0vZFX
          V/L1DLj+YpiU5ZAAABAQDb1s/dqqtrmPtIL1zmfkyO8fDdgkNZGWslW0N9B6JUf8kKJuvu
          S5CMpUNsLbUaKyrNAmouwJ6BThhDt4Lmaqusgp76WMNol9zeKeyu9gPV+uPAYvgYMW2mpj
          Iy3TlpGGPeESPk0CKNwmwXaiSF1YWvngGPE3cp+Qr3+G/TBQVmp6MC88GGkiPLas8shiGR
          CBrkm/agNsRA1lAei/MCLHf8llSgsuXFfdFjoe3UGEhkmXzkpJ3SF2mzli10AdI/tUYgt+
          dda5VzesO+TBx1pHWW2PrSZE1ALYX8/tkC27UguX6zTb6vNmFLH8wsma7UHF+WWNNfb4L2
          E0tuPRpiH2u9AAAAI2FzaWZhaG1lZEBBc2lmcy1NYWNCb29rLUFpci01LmxvY2FsAQIDBA
          UGBw==
          -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 174.138.56.3 >> ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa

      - name: SSH into Server
        run: |
          sshpass -p "unfold_studio" ssh -o StrictHostKeyChecking=no unfold_studio@174.138.56.3 "echo 'SSH connection established'"

      - name: Cache sudo password and Create File
        run: |
          sshpass -p "unfold_studio" ssh -o StrictHostKeyChecking=no unfold_studio@174.138.56.3 "echo 'unfold_studio' | sudo -S touch /opt/my_file.txt"
