name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
  push:
    branches:
      - issue_211

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Update lock file
        run: poetry lock
        
      - name: Install dependencies
        run: poetry install --with dev,docs,admin
        
      - name: Run tests
        run: |
          poetry run pytest unfold_studio/*/tests -v 

  run_integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Update lock file
        run: poetry lock
        
      - name: Install dependencies
        run: poetry install --with dev,docs,admin
        
      # - name: Install Chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: unfold_studio
          postgresql user: postgres
          postgresql password: postgres
          
      - name: Create CI settings file
        run: |
          cd unfold_studio
          cp unfold_studio/base_settings.py unfold_studio/settings.py
          echo "ALLOWED_HOSTS = ['localhost', '127.0.0.1']" >> unfold_studio/settings.py
          echo "DATABASES = {
              'default': {
                  'ENGINE': 'django.db.backends.postgresql',
                  'NAME': 'unfold_studio',
                  'USER': 'postgres',
                  'PASSWORD': 'postgres',
                  'HOST': 'localhost',
                  'PORT': '5432',
              }
          }" >> unfold_studio/settings.py
          
      - name: Start Django server
        env:
          PYTHONPATH: ${{ github.workspace }}
          DJANGO_SETTINGS_MODULE: unfold_studio.settings
        run: |
          cd unfold_studio
          poetry run python manage.py migrate
          poetry run python manage.py runserver 8000 &
          sleep 5  # Wait for server to start
          
      - name: Verify Django server is running
        run: |
          echo "Checking Django server response..."
          response=$(curl -s http://localhost:8000/)
          echo "Server response:"
          echo "$response"
          echo "$response" | grep -q "Django" || (echo "Django server is not running" && exit 1)
          echo "Django server is running successfully"
          
      # - name: Run integration tests
      #   env:
      #     PYTHONPATH: ${{ github.workspace }}
      #     CHROME_BIN: /usr/bin/chromium-browser
      #     CHROMEDRIVER_PATH: /usr/bin/chromedriver
      #     DJANGO_SETTINGS_MODULE: unfold_studio.settings
      #     TEST_URL: http://localhost:8000/stories/29/
      #   run: |
      #     poetry run python unfold_studio/integration_tests/test_input_generate.py
          