name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
  push:
    branches:
      - issue_211

env:
  POSTGRES_DB: unfold_studio
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: '5432'
  TEST_URL: http://localhost:8000/stories/29/
  CHROME_BIN: /usr/bin/chromium-browser
  CHROMEDRIVER_PATH: /usr/bin/chromedriver

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Update lock file
        run: poetry lock
        
      - name: Install dependencies
        run: poetry install --with dev,docs,admin
        
      - name: Run tests
        run: |
          poetry run pytest unfold_studio/*/tests -v 

  run_integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Update lock file
        run: poetry lock
        
      - name: Install dependencies
        run: poetry install --with dev,docs,admin
        
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql db: ${{ env.POSTGRES_DB }}
          postgresql user: ${{ env.POSTGRES_USER }}
          postgresql password: ${{ env.POSTGRES_PASSWORD }}
          
      - name: Create CI settings file
        run: |
          cd unfold_studio
          cp unfold_studio/base_settings.py unfold_studio/settings.py
          echo "ALLOWED_HOSTS = ['localhost', '127.0.0.1']" >> unfold_studio/settings.py
          echo "DATABASES = {
              'default': {
                  'ENGINE': 'django.db.backends.postgresql',
                  'NAME': '${{ env.POSTGRES_DB }}',
                  'USER': '${{ env.POSTGRES_USER }}',
                  'PASSWORD': '${{ env.POSTGRES_PASSWORD }}',
                  'HOST': '${{ env.POSTGRES_HOST }}',
                  'PORT': '${{ env.POSTGRES_PORT }}',
              }
          }" >> unfold_studio/settings.py
          echo "INK_DIR = os.path.join(BASE_DIR, 'ink')" >> unfold_studio/settings.py
          
      - name: Create required directories
        run: |
          cd unfold_studio
          mkdir -p ink
          chmod 777 ink
          
          # # Create media directory for file uploads
          # mkdir -p media
          # chmod 777 media
          
          # # Create static directory for static files
          # mkdir -p static
          # chmod 777 static
          
          # # Create logs directory
          # mkdir -p logs
          # chmod 777 logs
          
          # # Create temp directory
          # mkdir -p temp
          # chmod 777 temp
          
      - name: Install inklecate
        run: |
          cd unfold_studio
          wget https://github.com/inkle/ink/releases/download/v.1.2.0/inklecate_linux.zip
          unzip inklecate_linux.zip -d inklecate_1.2.0
          chmod +x inklecate_1.2.0/inklecate
          echo "INKLECATE = os.path.join(BASE_DIR, 'inklecate_1.2.0', 'inklecate')" >> unfold_studio/settings.py
          
      - name: Start Django server
        env:
          PYTHONPATH: ${{ github.workspace }}
          DJANGO_SETTINGS_MODULE: unfold_studio.settings
        run: |
          cd unfold_studio
          poetry run python manage.py makemigrations
          poetry run python manage.py migrate
          poetry run python manage.py runserver 8000 &
          sleep 5  # Wait for server to start
          
      - name: Verify Django server is running
        run: |
          echo "Checking Django server response..."
          response=$(curl -s http://localhost:8000/)
          echo "Server response:"
          echo "$response"
          echo "$response" | grep -q "Django" || (echo "Django server is not running" && exit 1)
          echo "Django server is running successfully"
          
      - name: Initialize test environment
        env:
          PYTHONPATH: ${{ github.workspace }}/unfold_studio:${{ github.workspace }}
          DJANGO_SETTINGS_MODULE: unfold_studio.settings
        run: |
          cd unfold_studio
          # poetry run python manage.py makemigrations
          # poetry run python manage.py migrate
          poetry run python -m integration_tests.initialization.initialize_test_environment
          
      - name: Run integration tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          DJANGO_SETTINGS_MODULE: unfold_studio.settings
        run: |
          for test_file in unfold_studio/integration_tests/tests/*.py; do
            if [ -f "$test_file" ]; then
              echo "Running test file: $test_file"
              poetry run python "$test_file"
            fi
          done
          